version: '3'

services:
  react:
    build:
      context: .
      dockerfile: ./.docker/react/Dockerfile
    container_name: react_container
    tty: true
    volumes:
      - ./react-app:/var/www/html
    command: sh -c "cd /var/www/html && npm start"
    ports:
      - 3000:3000

  api:
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    container_name: api_container
    ports:
      - 8000:8000
      - 2345:2345
    tty: true
    volumes:
      - ./api:/go/src/api
    command: "air -c .air.toml"

  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    container_name: nginx_container
    ports:
      - 443:443
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/ssl:/etc/nginx/ssl

  db:
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
    container_name: mysql_container
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/conf.d:/etc/mysql/conf.d
      - ./.docker/mysql/data:/var/lib/mysql
    tty: true
    environment:
      DB_MS: mysql
      DB_NAME: go_movie
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 3306
